### ISSUE TITLE
ERROR: Outlook Suite cannot access the OUTLOOK_DB_FILE

### ISSUE THREAD

**Issue by MingleiYang** [giovannicoppola/alfred-outlook#1]
Hi, 

Thank you for developing this app.

I came across this issue, where the OUTLOOK_DB_FILE cannnot be found.

could you give me some suggestions? Thanks.

09:55:27.775] Logging Started...
[09:55:30.577] Outlook Suite[Script Filter] Queuing argument '(null)'
[09:55:30.929] Outlook Suite[Script Filter] Script with argv '(null)' finished
[09:55:30.932] ERROR: Outlook Suite[Script Filter] Code 1: [{'Name': 'RecentUnread', 'Query': 'to:me is:unread since:20'}]
Database missing ... building ⏳
Traceback (most recent call last):
  File "/Users/myang/Dropbox/Alfred_backup/Alfred.alfredpreferences/workflows/user.workflow.953548F5-590D-4B81-9858-E5F77E6B9B9C/main.py", line 473, in <module>
    main()
  File "/Users/myang/Dropbox/Alfred_backup/Alfred.alfredpreferences/workflows/user.workflow.953548F5-590D-4B81-9858-E5F77E6B9B9C/main.py", line 413, in main
    checkingTime()
  File "/Users/myang/Dropbox/Alfred_backup/Alfred.alfredpreferences/workflows/user.workflow.953548F5-590D-4B81-9858-E5F77E6B9B9C/util.py", line 188, in checkingTime
    getFolderData()
  File "/Users/myang/Dropbox/Alfred_backup/Alfred.alfredpreferences/workflows/user.workflow.953548F5-590D-4B81-9858-E5F77E6B9B9C/util.py", line 78, in getFolderData
    db = sqlite3.connect(OUTLOOK_DB_FILE)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

**Comment by giovannicoppola** [comment]
@MingleiYang are you using the new Outlook, or the older version? This workflow only works with the older Outlook version.

**Comment by MingleiYang** [comment]
Hi, 

I switched back to the old version by unticking the "New Outlook", however, the issue is still there. 

I wonder how the program assigns the value for  the "OUTLOOK_DB_FILE" variable.


I printed out the "OUTLOOK_DB_FILE". variable and it showed this:

[18:47:28.216] Outlook Suite[Script Filter] /Users/giovanni/Desktop/Main Profile/Data/Outlook.sqlite
[18:47:28.217] ERROR: Outlook Suite[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
/Users/giovanni/Desktop/Main Profile/Data/Outlook.sqlite

it seems the default setting is your folder name.

thanks

**Comment by MingleiYang** [comment]
I change the corresponding variable in the consts.py.

however, there came other error, as shown below:

the main error is this "/Users/myang/Library/Application Support/Alfred/Workflow Data/giovanni-outlook/keyaccount.json'"

[18:59:33.420] Logging Started...
[18:59:36.472] Outlook Suite[Script Filter] Queuing argument '(null)'
[18:59:36.644] Outlook Suite[Script Filter] Script with argv '(null)' finished
[18:59:36.649] ERROR: Outlook Suite[Script Filter] Code 1: [{'Name': 'RecentUnread', 'Query': 'to:me is:unread since:20'}]
0 days from last update
Traceback (most recent call last):
  File "/Users/myang/Dropbox/Alfred_backup/Alfred.alfredpreferences/workflows/user.workflow.63B0E990-CCEB-43B6-A3A3-82E249E0DF56/main.py", line 420, in main
    myAccountKeys
UnboundLocalError: cannot access local variable 'myAccountKeys' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myang/Dropbox/Alfred_backup/Alfred.alfredpreferences/workflows/user.workflow.63B0E990-CCEB-43B6-A3A3-82E249E0DF56/main.py", line 473, in <module>
    main()
  File "/Users/myang/Dropbox/Alfred_backup/Alfred.alfredpreferences/workflows/user.workflow.63B0E990-CCEB-43B6-A3A3-82E249E0DF56/main.py", line 422, in main
    myAccountKeys = fetchAccounts ()
                    ^^^^^^^^^^^^^^^^
  File "/Users/myang/Dropbox/Alfred_backup/Alfred.alfredpreferences/workflows/user.workflow.63B0E990-CCEB-43B6-A3A3-82E249E0DF56/main.py", line 41, in fetchAccounts
    with open(OUTLOOK_ACCOUNT_KEY_FILE, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/myang/Library/Application Support/Alfred/Workflow Data/giovanni-outlook/keyaccount.json'

**Comment by MingleiYang** [comment]
it works after I outlook::refresh following the change of OUTLOOK_DB_FILE variable.

Thank you very much,
